---
- name: nickhammond.logrotate | Install logrotate
  package:
    name: logrotate
    state: present
  when: logrotate_scripts is defined and logrotate_scripts|length > 0

- name: nickhammond.logrotate | Setup logrotate.d scripts
  template:
    src: logrotate.d.j2
    dest: "{{ logrotate_conf_dir }}{{ item.name }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ logrotate_scripts }}"
  when: logrotate_scripts is defined

- name: ensure logrotate is enabled
  ansible.builtin.systemd:
    name: logrotate.timer
    enabled: yes
    state: started
