---
- name: Install logrotate
  ansible.builtin.package:
    name: logrotate
    state: present
  when: logrotate_scripts is defined and logrotate_scripts|length > 0

- name: Setup logrotate.d scripts
  ansible.builtin.template:
    src: logrotate.d.j2
    dest: "{{ logrotate_conf_dir }}{{ item.name }}"
    owner: root
    group: root
    mode: "0644"
  with_items: "{{ logrotate_scripts }}"
  when: logrotate_scripts is defined

- name: Check if logrotate.timer exists
  ansible.builtin.stat:
    path: /usr/lib/systemd/system/logrotate.timer
  register: logrotate_timer

- name: Ensure logrotate is enabled
  ansible.builtin.systemd:
    name: logrotate.timer
    enabled: true
    state: started
  when: logrotate_timer.stat.exists
